development:
  pdf_contract:
    NAME_STATE: 'RIO GRANDE DO NORTE'
    CONTRACT_JOIN: 'DEV - ENV - CONTRACT_JOIN'
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'
    LOAN: 'DEV - ENV - LOAN'
    DEPARTMENT_DEVELOPMENT: 'DEV - DEPARTMENT_DEVELOPMENT'
    FORO: Natal
    PRODUCTIVE_PROGRAM: 'DEV - PRODUCTIVE_PROGRAM'
    CREA: 'DEV - CREA'
    DEVELOPMENT_ACTION_COMPANY: 'DEV - DEVELOPMENT_ACTION_COMPANY'
  pdf_minute:
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'

test:
  pdf_contract:
    NAME_STATE: 'RIO GRANDE DO NORTE'
    CONTRACT_JOIN: 'TEST - ENV - CONTRACT_JOIN'
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'
    LOAN: 'TEST - ENV - LOAN'
    DEPARTMENT_DEVELOPMENT: 'TEST - DEPARTMENT_DEVELOPMENT'
    FORO: Natal
    PRODUCTIVE_PROGRAM: 'TEST - PRODUCTIVE_PROGRAM'
    CREA: 'TEST - CREA'
    DEVELOPMENT_ACTION_COMPANY: 'TEST - DEVELOPMENT_ACTION_COMPANY'
  pdf_minute:
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'

production:
  pdf_contract:
    NAME_STATE: 'RIO GRANDE DO NORTE'
    CONTRACT_JOIN: 'ENV - CONTRACT_JOIN'
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'
    LOAN: 'ENV - LOAN'
    DEPARTMENT_DEVELOPMENT: 'DEPARTMENT_DEVELOPMENT'
    FORO: Natal
    PRODUCTIVE_PROGRAM: 'PRODUCTIVE_PROGRAM'
    CREA: 'CREA'
    DEVELOPMENT_ACTION_COMPANY: 'DEVELOPMENT_ACTION_COMPANY'
  pdf_minute:
    COVENANT_RESOURCE: 'Projeto Integrado de Desenvolvimento Sustentavel'
